export const ADD_EMPLOYEES_START = 'ADD_EMPLOYEES_START';
export const ADD_EMPLOYEES_SUCCESS = 'ADD_EMPLOYEES_SUCCESS';
export const ADD_EMPLOYEES_ERROR = 'ADD_EMPLOYYES_ERROR';

export const ADD_DEPARTMENTS_START = 'ADD_DEPARTMENTS_START';
export const ADD_DEPARTMENTS_SUCCESS = 'ADD_DEPARTMENTS_SUCCESS';
export const ADD_DEPARTMENTS_ERROR = 'ADD_DEPARTMENTS_ERROR';

export const GET_EMPLOYEES_START = 'GET_EMPLOYEES_START';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';

export const GET_DEPARTMENTS_START = 'GET_DEPARTMENTS_START';
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENTS_ERROR = 'GET_DEPARTMENTS_ERROR';

export const UPDATE_EMPLOYEES_START = 'UPDATE_EMPLOYEES_START';
export const UPDATE_EMPLOYEES_SUCCESS = 'UPDATE_EMPLOYEES_SUCCESS';
export const UPDATE_EMPLOYEES_ERROR = 'UPDATE_EMPLOYYES_ERROR';

export const UPDATE_DEPARTMENTS_START = 'UPDATE_DEPARTMENTS_START';
export const UPDATE_DEPARTMENTS_SUCCESS = 'UPDATE_DEPARTMENTS_SUCCESS';
export const UPDATE_DEPARTMENT_ERROR = 'UPDATE_DEPARTMENTS_ERROR';

export const DELETE_EMPLOYEES_START = 'DELETE_EMPLOYEES_START';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_ERROR = 'DELETE_EMPLOYYES_ERROR';

export const DELETE_DEPARTMENTS_START = 'DELETE_DEPARTMENTS_START';
export const DELETE_DEPARTMENTS_SUCCESS = 'DELETE_DEPARTMENTS_SUCCESS';
export const DELETE_DEPARTMENT_ERROR = 'DELETE_DEPARTMENTS_ERROR';
